# yamllint configuration for ScriptRAG project
# https://yamllint.readthedocs.io/en/stable/configuration.html

extends: default

# Rules configuration
rules:
  # Line rules
  line-length:
    max: 100
    level: warning
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true

  # Indentation rules
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false

  # Document rules
  document-start:
    present: false

  document-end:
    present: false

  # Quoted strings - disable to avoid conflicts
  quoted-strings: disable

  # Brackets - disable to avoid conflicts
  brackets: disable

  # Truthy values
  truthy:
    allowed-values: ['true', 'false']
    check-keys: false
    level: warning

# File ignore patterns
ignore: |
  .venv/
  venv/
  node_modules/
  .tox/
  build/
  dist/
  *.egg-info/
  htmlcov/
  .mypy_cache/
  .pytest_cache/
  .ruff_cache/
  .git/
  site/

# vim: ft=yaml
