site_name: ScriptRAG
site_description: "Semantic graph for screenplay analysis and querying using GraphRAG"
site_url: "https://trieloff.github.io/scriptrag"
repo_url: "https://github.com/trieloff/scriptrag"
repo_name: "trieloff/scriptrag"

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - API Documentation:
      - Overview: API.md
      - API Reference: api-reference.md
      - User Guide: user-guide.md
      - Developer Guide: developer-guide.md
      - Architecture: architecture.md
  - Development: development.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: teal
      accent: lime

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_source: true
            show_root_heading: true

docs_dir: docs
use_directory_urls: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.mark
  - attr_list
  - md_in_html
  - tables

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js

extra_css:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.css
